name: Ruffinweb Cloudfront/S3 Workflow

on:
  push:
    branches:
      - 'master'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app-dist
          path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app-dist
          path: './dist'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::230114978033:role/OIDCGithubActionsDefault
          role-session-name: S3CloudfrontWorkflowSession
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_PRODUCTION }}

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }} --paths '/*'
